- name: fisher
  shell: fisher
  args:
    executable: "{{ fish_binary_path }}"

- name: setup_fish
  shell: /tmp/setup-fish.sh
  args:
    creates: "{{ fish_config_dir }}/functions/fish_prompt.fish"
