---
- name: Add {{ role_name }} Debian repository
  apt_repository:
    repo: "{{ fish_repository }}"
    update_cache: true

- name: Install {{ role_name }}
  apt:
    package: "{{ fish_packages }}"

#- name: Install ccat
#  unarchive:
#    src: "{{ ccat_url }}"
#    dest: /usr/local/bin/ccat
#    remote_src: true

- name: Set as default shell
  user:
    user: "{{ ansible_user }}"
    shell: "{{ fish_binary_path }}"

- name: Check if {{ role_path }} configs directory exist
  file:
    state: directory
    recurse: true
    dest: "{{ fish_config_dir }}/functions"

- name: Check if starship is installed
  stat:
    path: '{{ starship_binary_path }}'
  changed_when: False
  register: starship_binary

- name: Install starship prompt
  get_url:
    url: "{{ starship_url }}"
    dest: /tmp/starship.sh
    mode: a+x
  notify: starship

- name: Configure {{ role_name }} from templates
  template:
    src: "{{ config_file }}.j2"
    dest: "{{ config_dir }}/{{ config_file }}"
  loop:
    - starship.toml
    - fish/config.fish
    - fish/fish_variables
    - fish/fish_variables
  loop_control:
    loop_var: config_file

- name: Install fisher
  get_url:
    url: https://git.io/fisher
    dest: "{{ fish_config_dir }}/functions/fisher.fish"
    mode: a+x
  notify: fisher

- name: Install {{ role_name }} ssh extension
  unarchive:
    src: https://github.com/xxh/xxh-portable/raw/master/result/xxh-portable-musl-alpine-Linux-x86_64.tar.gz
    remote_src: true
    dest: /usr/local/bin/
    creates: xxh
