---
- name: Add {{ role_name }} Debian repository
  apt_repository:
    repo: "{{ fish_repository }}"
    update_cache: true

- name: Install {{ role_name }}
  apt:
    package: "{{ fish_packages }}"

#- name: Install ccat
#  unarchive:
#    src: "{{ ccat_url }}"
#    dest: /usr/local/bin/ccat
#    remote_src: true

- name: Set as default shell
  user:
    user: "{{ ansible_user }}"
    shell: "{{ fish_binary_path }}"

- name: Check if {{ role_path }} configs directory exist
  file:
    state: directory
    recurse: true
    dest: "{{ fish_config_dir }}/functions"

- name: Check if starship is installed
  stat:
    path: '{{ starship_binary_path }}'
  changed_when: False
  register: starship_binary

- when: not starship_binary.stat.exists
  name: Install starship prompt
  shell: curl {{ starship_url }} | bash
  args:
    creates: "{{ starship_binary_path }}"
  environment:
    FORCE: "1"

- name: Configure {{ role_name }} from templates
  template:
    src: "{{ config_file}}.j2"
    dest: "{{ config_dir }}/{{ config_file }}"
  loop:
    - starship.toml
    - fish/config.fish
  loop_control:
    loop_var: config_file

- name: Configure {{ role_name }} from templates
  template:
    src: fish/fishfile.j2
    dest: "{{ fish_config_dir }}/fishfile"
  register: fishfile

- name: Install fisher
  get_url:
    url: https://git.io/fisher
    dest: "{{ fish_config_dir }}/functions/fisher.fish"
  when: fishfile.changed

- name: Install {{ role_name }} plugins
  shell: "{{ fish_binary_path }} -C 'fisher'"
  changed_when: false

- name: Configure {{ role_name }} colors
  blockinfile:
    path: "{{ fish_config_dir }}/fish_variables"
    block: |
      SETUVAR fish_color_autosuggestion:yellow
      SETUVAR fish_color_cancel:normal
      SETUVAR fish_color_command:brgreen
      SETUVAR fish_color_comment:969696
      SETUVAR fish_color_cwd:cyan
      SETUVAR fish_color_cwd_root:brcyan
      SETUVAR fish_color_end:red
      SETUVAR fish_color_error:red
      SETUVAR fish_color_escape:brmagenta
      SETUVAR fish_color_history_current:brcyan
      SETUVAR fish_color_host:green
      SETUVAR fish_color_host_remote:red
      SETUVAR fish_color_match:green
      SETUVAR fish_color_normal:brwhite
      SETUVAR fish_color_operator:brred
      SETUVAR fish_color_param:magenta
      SETUVAR fish_color_quote:bryellow
      SETUVAR fish_color_redirection:brred
      SETUVAR fish_color_search_match:\x2d\x2dbackground\x3d969696
      SETUVAR fish_color_selection:brcyan
      SETUVAR fish_color_status:yellow
      SETUVAR fish_color_user:green
      SETUVAR fish_color_valid_path:brblue
      SETUVAR fish_greeting:''
      SETUVAR fish_key_bindings:fish_default_key_bindings
      SETUVAR fish_pager_color_completion:white
      SETUVAR fish_pager_color_description:969696
      SETUVAR fish_pager_color_prefix:brmagenta
      SETUVAR fish_pager_color_progress:cyan

- name: Install {{ role_name }} ssh extension
  unarchive:
    src: https://github.com/xxh/xxh-portable/raw/master/result/xxh-portable-musl-alpine-Linux-x86_64.tar.gz
    remote_src: true
    dest: /usr/local/bin/
    creates: xxh
