---
- name: Add {{ role_name }} Debian repository
  apt_repository:
    repo: "{{ fish_repository }}"
    update_cache: true

- name: Install {{ role_name }}
  apt:
    package: "{{ fish_packages }}"

#- name: Install ccat
#  unarchive:
#    src: "{{ ccat_url }}"
#    dest: /usr/local/bin/ccat
#    remote_src: true

- name: Set as default shell
  user:
    user: "{{ ansible_user }}"
    shell: "{{ fish_binary_path }}"

- name: Download {{ role_name }} setup script
  get_url:
    url: "{{ fish_setup_script_url }}"
    dest: /tmp/setup-fish.sh
  notify: setup_fish

- name: Install {{ role_name }} dependency manager
  get_url:
    url: https://git.io/fisher
    dest: "{{ fish_config_dir }}/functions/fisher.fish"
    mode: a+x
  notify: fisher
