---
- name: Install {{ role_name }} utilities repository
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Set as default shell
  user:
    user: "{{ ansible_user }}"
    shell: "{{ fish_binary_path }}"

- name: Download {{ role_name }} setup script
  get_url:
    url: "{{ fish_setup_script_url }}"
    dest: /tmp/setup-fish.sh
    mode: a+x
  notify: setup_fish
