wsl_utilities_deb_repository: "deb https://access.patrickwu.space/wslu/debian buster main"
wsl_utilities_deb_repository_key: "https://access.patrickwu.space/wslu/public.asc"
wsl_config:
  user:
    default: "root"
  automount:
    enabled: "true"
    root: "/"
    options: "metadata,umask=22,fmask=111"
    mount_fs_tab: "true"
  network:
    generate_hosts: "true"
    generate_resolv_conf: "true"
  interop:
    enabled: "false"
    append_windows_path: "false"
