---
- name: Install {{ role_name }}
  unarchive:
    src: "{{ helm_url }}"
    remote_src: true
    dest: "{{ bin_dir }}"
    creates: "{{ bin_dir }}/helm"
    extra_opts: [--strip=1]

- name: Install Helmfile
  get_url:
    url: "{{ helmfile_url }}"
    dest: "{{ bin_dir }}/helmfile"
    mode: a+x

- name: Install {{ role_name }} diff plugin
  shell: helm plugin install https://github.com/databus23/helm-diff --version master
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/helm/plugins/helm-diff/bin/diff"
