fish_repository: ppa:fish-shell/release-3
fish_setup_script_url: https://raw.githubusercontent.com/Hiberbee/fish-shell/master/init.sh
ccat_url: https://github.com/jingweno/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz
paths:
  - /usr/local/bin
fish_packages:
  - fish
env_vars:
  COLORTERM: truecolor
  DOCKER_BUILDKIT: 1
  EDITOR: nano
  FISH_KUBECTL_COMPLETION_COMPLETE_CRDS: 1
  FISH_KUBECTL_COMPLETION_TIMEOUT: 0
  HELMFILE_EXPERIMENTAL: 1
  HELM_EXPERIMENTAL_OCI: 1
  MINIKUBE_IN_STYLE: false
fish_binary_path: /bin/fish
fish_config_dir: "{{ lookup('env', 'HOME') }}/.config/fish"
