apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: ansible-collection-devops
build:
  local:
    concurrency: 0
    useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ubuntu
      docker:
        target: ubuntu
    - image: debian
      docker:
        target: debian
test:
  - image: ubuntu
    structureTests: [structure-test.yaml]
  - image: debian
    structureTests: [structure-test.yaml]
