apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: ansible-collection-devops
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ubuntu
      docker:
        target: ubuntu
    - image: debian
      docker:
        target: debian
