- name: Install {{ role_name }} dependencies
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Check if {{ role_name }} directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.ssh/"
  register: ssh_directory

- name: Fix {{ role_name }} keys permissions
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh/{{ public_key }}.pub"
    mode: '0640'
  loop: "{{ ssh_keys }}"
  loop_control:
    loop_var: public_key
  when: ssh_directory.stat.exists

- name: Fix {{ role_name }} keys permissions
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh/{{ private_key }}"
    mode: '0600'
  loop: "{{ ssh_keys }}"
  loop_control:
    loop_var: private_key
  when: ssh_directory.stat.exists

- name: Create {{ role_name }} PID directory
  file:
    path: "{{ directory }}"
    state: directory
  loop:
    - "{{ sshd_pid_path }}"
    - "{{ sshd_config_path }}"
  loop_control:
    loop_var: directory
  when: ssh_directory.stat.exists

- name: Configure {{ role_name }} from template
  template:
    src: wsl.conf.j2
    dest: "{{ sshd_config_path }}/wsl.conf"
    validate: "{{ sshd_binary }} -t -f %s"
  when: ssh_directory.stat.exists

- name: Add {{ role_name }} authorized keys
  authorized_key:
    state: present
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + public_key + '.pub') }}"
  loop: "{{ ssh_keys }}"
  loop_control:
    loop_var: public_key
  when: ssh_directory.stat.exists

- name: Install {{ role_name }} systemd service
  template:
    src: "sshd.service.j2"
    dest: /etc/systemd/system/sshd.service
  when: ssh_directory.stat.exists

- name: Service enabled and running
  service:
    name: ssh
    enabled: true
    state: started
  when: ssh_directory.stat.exists

- name: Start {{ role_name }} service
  service:
    name: sshd
    state: started
    enabled: true
  when: ssh_service_started
