---
- name: Install {{ role_name }} dependencies
  apt:
    package: "{{ sdkman_dependencies }}"

- name: Download {{ role_name }} SDK manager installer script
  get_url:
    url: "{{ sdkman_url }}"
    dest: /tmp/sdkman.sh
    mode: a+x
  notify: sdkman
