---
- name: Install {{ role_name }} utilities repository
  include_tasks: "{{ ansible_os_family | lower }}.yml"


- name: Download {{ role_name }} SDK manager installer script
  get_url:
    url: "{{ sdkman_url }}"
    dest: /tmp/sdkman.sh
    mode: a+x
  notify: sdkman
