---
- name: Install {{ role_name }} CLI client
  get_url:
    url: "{{ kubernetes_url }}"
    dest: /usr/local/bin/kubectl
    mode: a+x
    force: true

- name: Install {{ role_name }} Kops client
  get_url:
    url: "{{ kops_url }}"
    dest: /usr/local/bin/kops
    mode: a+x
    force: true

- name: Install {{ role_name }} Minikube
  get_url:
    url: "{{ minikube_url }}"
    dest: /usr/local/bin/minikube
    mode: a+x
    force: true
