---
- name: Install {{ role_name }} v{{ terraform_version }}
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    remote_src: true
    dest: "{{ bin_dir }}"
    creates: "{{ bin_dir }}/terraform"
    mode: a+x
