---
- name: Install {{ role_name }} v{{ terraform_version }}
  unarchive:
    src: "{{ terraform_url }}"
    remote_src: true
    dest: "{{ bin_dir }}"
    creates: "{{ bin_dir }}/terraform"
    mode: a+x
