- name: Install {{ role_name }} utilities repository
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Configure {{ role_name }}
  template:
    src: wsl.conf.j2
    dest: /etc/wsl.conf
