---
- name: Add {{ role_name }} repository key
  apt_key:
    url: "{{ docker_deb_repository_key }}"

- name: Install {{ role_name }} repository
  apt_repository:
    repo: "{{ docker_deb_repository }}"
    update_cache: true

- name: Install {{ role_name }} dependencies
  apt:
    package: docker-ce

- name: Install {{ role_name }} python packages
  pip:
    name: "{{ pip_package }}"
    executable: /usr/bin/pip3
  loop: "{{ pip_packages }}"
  loop_control:
    loop_var: pip_package

- name: Create {{ role_name }} config directory
  file:
    path: "{{ directory }}"
    state: directory
  loop:
    - /root/.docker
    - /etc/docker
  loop_control:
    loop_var: directory

- name: Configure {{ role_name }}
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Configure {{ role_name }} systemd service
  template:
    src: "{{ template }}.j2"
    dest: /etc/systemd/system/{{ template }}
  loop:
    - docker.service
    - docker.socket
  loop_control:
    loop_var: template

- name: Setup {{ role_name }} registry
  include_tasks: registry.yml

- name: Setup {{ role_name }} tools
  include_tasks: hadolint.yml

- name: Start {{ role_name }} service
  service:
    name: docker
    state: started
    enabled: true
  when: docker_service_started
