---
- name: Install {{ role_name }}
  unarchive:
    src: "{{ docker_url }}"
    remote_src: true
    dest: "{{ bin_dir }}"
    creates: "{{ bin_dir }}/docker"
    extra_opts: [--strip=1]

- name: Install {{ role_name }} python packages
  pip:
    name: "{{ docker_pip_dependency }}"
    executable: /usr/bin/pip3
  loop: "{{ docker_pip_dependencies }}"
  loop_control:
    loop_var: docker_pip_dependency

- name: Create {{ role_name }} config directory
  file:
    path: "{{ directory }}"
    state: directory
  loop:
    - /root/.docker
    - /etc/docker
  loop_control:
    loop_var: directory

- name: Configure {{ role_name }}
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Configure {{ role_name }} systemd service
  template:
    src: "{{ template }}.j2"
    dest: /etc/systemd/system/{{ template }}
  loop:
    - docker.service
    - docker.socket
  loop_control:
    loop_var: template

- name: Setup {{ role_name }} tools
  include_tasks: hadolint.yml

- name: Start {{ role_name }} service
  service:
    name: docker
    state: started
    enabled: true
  when: docker_service_started

- name: Setup {{ role_name }} registry
  include_tasks: registry.yml
  when: docker_service_started
